name: Nightly Test run (Jahia Release)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  integration-tests-rl:
    uses:  Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee:8
      module_id: server-availability-manager
      testrail_project: Server Availability Manager
      pagerduty_incident_service: server-availability-manager-JahiaRL
      provisioning_manifest: provisioning-manifest-snapshot.yml
      module_branch: ${{ github.ref }}
