name: Nightly Test run (Jahia Snapshot)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  integration-tests-sn:
    uses:  Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee-dev:8-SNAPSHOT
      module_id: server-availability-manager
      testrail_project: Server Availability Manager
      pagerduty_incident_service: server-availability-manager-JahiaSN
      provisioning_manifest: provisioning-manifest-snapshot.yml
      module_branch: ${{ github.ref }}
